[package]
name = "rusty-mud-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.3.1"
rusty-mud-common = { path = "../rusty-mud-common" }
zxcvbn = "2.2.1"
